name: Validate
on: [push]
env:
  CI: true

jobs:
  # If you put "[skip ci]" in the commit message, it won't run the checks/test.
  # https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
  proceed:
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
    steps:
      - run: |
          cat <<'MESSAGE'
          github.event_name: ${{ toJson(github.event_name) }}
          github.event:
          ${{ toJson(github.event) }}
          MESSAGE

  check:
    needs: proceed
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Check Types
        run: yarn typecheck

      - name: Test
        run: yarn test
